# Generated by Django 3.0.2 on 2020-01-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=' ')),
                ('title', models.CharField(default=' ', max_length=50)),
                ('genre', models.CharField(default=' ', max_length=50)),
                ('description', models.TextField(default=' ')),
                ('director', models.CharField(default=' ', max_length=50)),
                ('actors', models.TextField(default=' ')),
                ('year', models.IntegerField(default=' ')),
                ('rating', models.IntegerField(default=' ')),
            ],
        ),
    ]
