# Generated by Django 3.0.2 on 2020-01-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=' ', max_length=50)),
                ('watched_movies', models.IntegerField(default=' ')),
                ('action', models.IntegerField(default=' ')),
                ('adventure', models.IntegerField(default=' ')),
                ('scifi', models.IntegerField(default=' ')),
                ('mystery', models.IntegerField(default=' ')),
                ('horror', models.IntegerField(default=' ')),
                ('thriller', models.IntegerField(default=' ')),
                ('animation', models.IntegerField(default=' ')),
                ('comedy', models.IntegerField(default=' ')),
                ('family', models.IntegerField(default=' ')),
                ('fantasy', models.IntegerField(default=' ')),
                ('drama', models.IntegerField(default=' ')),
                ('music', models.IntegerField(default=' ')),
                ('biography', models.IntegerField(default=' ')),
                ('romance', models.IntegerField(default=' ')),
                ('history', models.IntegerField(default=' ')),
                ('crime', models.IntegerField(default=' ')),
                ('western', models.IntegerField(default=' ')),
                ('war', models.IntegerField(default=' ')),
                ('musical', models.IntegerField(default=' ')),
                ('sport', models.IntegerField(default=' ')),
            ],
        ),
        migrations.RenameModel(
            old_name='Movies_List',
            new_name='MoviesList',
        ),
    ]
