# Generated by Django 3.0.2 on 2020-01-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfapp', '0002_auto_20200129_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviessuggestions',
            name='watched_movies',
            field=models.TextField(default=' '),
        ),
    ]
