# Generated by Django 3.0.2 on 2020-01-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfapp', '0003_auto_20200129_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviessuggestions',
            name='action',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='adventure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='animation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='biography',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='comedy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='crime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='drama',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='family',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='fantasy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='history',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='horror',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='music',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='musical',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='mystery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='romance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='scifi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='sport',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='thriller',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='war',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviessuggestions',
            name='western',
            field=models.IntegerField(default=0),
        ),
    ]
